### ISSUE TITLE
Restarting Discord causes it to fail detecting Nervegear

### ISSUE THREAD

**Issue by sponnify** [TenDRILLL/Nervegear#4]
Restarting Discord causes it to fail to detect Nervegear. This is solved by closing Nervegear and reopening it again; minor inconvenience. 

Running Nervegear 2.2.9c on Windows 11, latest Discord update.

**Comment by TenDRILLL** [comment]
Thank you for the report, I'll take a look at auto-restarting the application in case it loses the connection to Discord.

**Comment by TenDRILLL** [comment]
Commit 22dd8afa5cbbf4c8ea0b8da92371eab04b49d37f fixes mentioned issue, and will be available in the next release.
