### ISSUE TITLE
"Choose Game" popup stuck on screen

### ISSUE THREAD

**Issue by sponnify** [TenDRILLL/Nervegear#5]
Clicking on the _Choose Game_ button again *after* selecting a game and clicking _Start_ with the panel still open causes it to become stuck on the screen.

Running Nervegear 2.2.9c, Windows 11.

**Comment by TenDRILLL** [comment]
Ah, didn't think of that. Thanks for reporting it, will fix ^^

**Comment by TenDRILLL** [comment]
Commit 2b143245f045820d9df842df6d444f9c9cf0de93 fixes mentioned issue, and will be available in the next release.
